### PR TITLE
Added support for search_type and scroll URI parameters to search.

### PR DESCRIPTION
**Pull request by mmollaverdi**
For additional type safety and expressiveness, I've used case classes to model URI parameters and search types. The SearchUriParameters case class can be extended further for more URI parameters in future as per this document:
http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-uri-request.html

@Maintainers, let me know if it's not inline with the original design principles of this library.

### CODE REVIEW

**Comment by gphat** [comment]
Hey @mmollaverdi!

This looks good. Could I trouble you to add some documentation to the README to explain the use of this? Then I'm quite happy to merge it.

**Comment by mmollaverdi** [comment]
Hi @gphat 
Sure, will do today.

**Comment by mmollaverdi** [comment]
@gphat Please see my last 2 commits appended to this PR.

**Comment by mmollaverdi** [comment]
@gphat Just wondering if you've had a chance to review my latest commits to this PR.

**Comment by gphat** [comment]
Hey @mmollaverdi! Just looking at it now! :)

**Comment by gphat** [comment]
I think we're on right track, but you only really documented the `Scan` and `Count`. Maybe add a section the enumerates each one and describes their uses?

Sorry to be picky. This seems useful, but I want to make sure that people can find it and benefit from it!

**Comment by mmollaverdi** [comment]
No, that's alright.

How about I link to [the reference document for search types](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-request-search-type.html) on elasticsearch website, in that section of the README file?

I can copy/paste what's in there, but that would be redundant and can become out-of-date in future.

**Comment by mmollaverdi** [comment]
@gphat Just added a link to documentation on different search types, plus more explanation of given examples.

Let me know if you still think documentation on each individual search type is needed.

**Comment by gphat** [comment]
Sorry @mmollaverdi, I was busy with some other things.

From reading your documentation it's still unclear to me how a user would know of all the convenience classes you've created for them to use. You explain `Count`, but none of the others. Am I misreading the documentation? Are you expecting them to find them through some other means, such as the Scaladoc?

Again, sorry to be so picky for the reasons I already explained. :smile_cat:

**Comment by mmollaverdi** [comment]
@gphat Sorry just trying to figure out the best way to document this.
So, the case objects defined on [lines 487 to 492](https://github.com/mmollaverdi/wabisabi/blob/search-uri-parameters/src/main/scala/wabisabi/Client.scala#L487-L492) each represent a specific search type as per this [reference document](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html#query-then-fetch). The name of each case object, nicely maps to the name of a specific search type, e.g. `QueryAndFetch` represents `query_and_fetch`. 
And each of the search type case objects can be used as the value for `searchType` attribute in an instance of `SearchUriParameters` case class, when calling search methods, as can be seen in my examples.

I can still add Scaladocs to the case objects and SearchUriParameters case class if that helps?

**Comment by gphat** [comment]
Okey doke, I'll leave it as is. Merged and released as 2.1.2. Thanks again for all your contributions, @mmollaverdi!

**Comment by mmollaverdi** [comment]
@gphat Sorry I somehow missed your last comment. Thanks for merging and releasing it.

**Pull request merged**
