### PR TITLE
Remove URL parsing, as I'm not sure what it adds.

### PR DESCRIPTION
**Pull request by gphat**
First, let me apologize for merging this without looking at it closely. :(

Hey @jfelectron, I wonder if you could chime in here and help me with this?

You're #10 parses the URL and re-adds them do the dispatch URL. How is this better or different from using the username and password encoded into the URL itself? Perhaps I'm missing something about dispatch. :)

Also, this I'd like @blast-hardcheese's feedback too since this change (as it stands) would return us to the previous default behavior.

I'd like to get both the auth functionality and the previous behavior back.

### CODE REVIEW

**Comment by blast-hardcheese** [comment]
I'm not familiar with dispatch, but while it looks like it handles url auth parameters, I see no mention of them anywhere in either docs or tests. That being said, if it is actually missing, we should file an issue with them instead of trying to work around it here.

Does it work in your test environment? I'm not set up to test this issue.

**Comment by gphat** [comment]
Im not either, as @jfelectron didn't include a test and I didn't ask. :(

I'll wait around for a bit to see if he responds.

**Comment by jfelectron** [comment]
@gphat @blast-hardcheese  Yes, it added support for url auth, both basic auth and ssl.  The test suite was broken at the time, so I never added a test. How about your create a doc issue and assingn it to me? Also, wabisabi really needs to be refactored with the re-write of dispact. The APIs have changed quite  a bit and many of the old one's are deprecated.

**Comment by dmitry-egorov** [comment]
Just to add my 50 cents, when I was fiddling with dispatch about 3 weeks ago, it ignored auth parameters in url. I had to put them explicitly into the dispatch request object.

**Comment by gphat** [comment]
Yup, I've dug in and see that ignoring the HTTP auth params is indeed the behavior. Thanks for the note @dmitry-egorov.

I'll update this PR with a few things in a bit. Thanks for chiming in, everyone!

**Comment by jfelectron** [comment]
Not sure what you mean, here is an example. You can generate the url before creating the dispatch request object. 
```scala

case class ESConf(host: String, ssl: Boolean, auth: String, port: Int)

    def gen_es_url(es_conf: ESConf): String = {
      val host = es_conf.host
      val port = es_conf.port
      val ssl = es_conf.ssl
      val auth = es_conf.auth
      val es_url = if (auth.isEmpty) {
        s"http://$host:$port"
      }
      else if (ssl) {
        s"https://$auth@$host:$port"
      }
      else {
        s"http://$auth@$host:$port"
      }

      logger.info(s"ES URL: $es_url")
      es_url
    }

   def get_req(es_url: String) = {

      val uri: Uri = es_url

      val req = if (uri.user.isDefined && uri.password.isDefined) {
        logger.info("generating http auth url")
        val (user, pw) = (uri.user.get, uri.password.get)
        println(s"user: $user pw: $pw ")
        dispatch.url(uri.protocol.get + "://" + uri.host.get + ":" + uri.port.get).as_!(user, pw)
      }

      else {
        logger.info("generatng unsecured url")
        dispatch.url(uri.protocol.get + "://" + uri.host.get + ":" + uri.port.get)

      }
```

**Comment by jfelectron** [comment]
Only with the old dispatch your using, which is broken in many ways The
code sample works with the new dispatch.

On Sun, Jan 4, 2015 at 5:51 PM, Cory G Watson <notifications@github.com>
wrote:

> Yup, I've dug in and see that ignoring the HTTP auth params is indeed the
> behavior. Thanks for the note @dmitry-egorov
> <https://github.com/dmitry-egorov>.
>
> I'll update this PR with a few things in a bit. Thanks for chiming in,
> everyone!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gphat/wabisabi/pull/13#issuecomment-68660027>.
>



-- 
*__________________*
*Jonathan Foley*
VP of Science| Gild, Inc.
800-664-2366  | *cell 510-725-8484*

465 California Street, Suite 1250
San Francisco, CA 94104
www.gild.com

**Comment by gphat** [comment]
Sorry, I don't follow dispatch's development. What's this old version / new version stuff? Even in local testing with 0.11.2 (the latest as found [at the website](http://dispatch.databinder.net/Dispatch.html)) I still see the auth params ignored.

**Comment by jfelectron** [comment]
Yes, dispatch-core 0.11.2

The're aren't params per-se, as you can create the url that is then parsed
by dispatch. This work in production with both basic auth and https.

 dispatch.url(uri.protocol.get + "://" + uri.host.get + ":" +
uri.port.get).as_!(user, pw)

On Sun, Jan 4, 2015 at 6:16 PM, Cory G Watson <notifications@github.com>
wrote:

> Sorry, I don't follow dispatch's development. What's this old version /
> new version stuff? Even in local testing with 0.11.2 (the latest as found at
> the website <http://dispatch.databinder.net/Dispatch.html>) I still see
> the auth params ignored.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gphat/wabisabi/pull/13#issuecomment-68661146>.
>



-- 
*__________________*
*Jonathan Foley*
VP of Science| Gild, Inc.
800-664-2366  | *cell 510-725-8484*

465 California Street, Suite 1250
San Francisco, CA 94104
www.gild.com

**Comment by gphat** [comment]
I'm running a local test of this with [http-basic](https://github.com/Asquera/elasticsearch-http-basic) and your change (using `as_!`) doesn't work for me.

What are you using to put basic auth in front of your ES? That would help me test.

I will update the version of dispatch, but I consider that to be a tangential issue.

**Comment by gphat** [comment]
Note that the small missing `}` in the test suite was fixed (not sure how that got there!) and the versions of Scala and the underlying deps have all been brought up to snuff in master and merged to this branch.

Again, please let me know how you've got your basic auth set up @jfelectron because my local tests with [http-basic](https://github.com/Asquera/elasticsearch-http-basic) don't work and I'd love to find a way to test this locally before proceeding.

**Comment by jfelectron** [comment]
NginX



On Sun, Jan 4, 2015 at 6:25 PM, Cory G Watson <notifications@github.com>
wrote:

> I'm running a local test of this with http-basic
> <https://github.com/Asquera/elasticsearch-http-basic> and your change
> (using as_!) doesn't work for me.
>
> What are you using to put basic auth in front of your ES? That would help
> me test.
>
> I will update the version of dispatch, but I consider that to be a
> tangential issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gphat/wabisabi/pull/13#issuecomment-68661549>.
>



-- 
*__________________*
*Jonathan Foley*
VP of Science| Gild, Inc.
800-664-2366  | *cell 510-725-8484*

465 California Street, Suite 1250
San Francisco, CA 94104
www.gild.com

**Pull request closed without merging**
