### PR TITLE
Correct few typos in README.md

### PR DESCRIPTION
**Pull request by pvigier**
I just correct few typos in the examples given in README.md

### CODE REVIEW

**Comment by gphat** [comment]
Hey @pvigier, this has some conflicts after merging some other corrections. Do you mind rebasing?

**Comment by pvigier** [comment]
Is it OK now ?

**Comment by gphat** [comment]
I'm… not sure what you did, but now it's in a very weird state. Lemme see if I can fix.

**Comment by gphat** [comment]
I think another PR got some of these. I straightened out some space as well. Closing this. Lemme know if you find anything else.

**Pull request closed without merging**
