### PR TITLE
add docAsUpsert method

### PR DESCRIPTION
**Pull request by suya55**
Added docAsUpsert method to Client.scala
* Adds or updates a JSON documented of the specified type in the specified
* index using https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html?q=update#upserts

### CODE REVIEW

**Comment by gphat** [comment]
Ugh. How did I miss this! Looking it over now!

**Comment by gphat** [comment]
Hey @suya55, sorry for being so slow about this.

So wabisabi doesn't currently have an update method. What do you think of changing this to be an `update` method and making the option to upsert an argument?

I'm happy to make the adjustments, but am curious as to your thoughts!

**Comment by suya55** [comment]
@gphat, Thank you for accepting my pull-request.

I agree with you. Having options in ```update``` method should be better. script, doc and doc_as_upsert.( According to [Elasticsearch reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html?q=update#upserts).)
In my opinion, that's good idea.

**Comment by gphat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
